### PR TITLE
Propose New var Structure

### PR DESCRIPTION
**Pull request by jjaswanson4**
Merge the best of @flyemsafe and @jjaswanson4 var structure, proposed structure for vars going forward

### CODE REVIEW

**Comment by greg-hellings** [comment]
Just a brief complaint: in the future can we avoid using work branches inside of this repository? Please pull them in from a personal fork in the future. It makes things cleaner, especially stuff like tags.

**Comment by jjaswanson4** [comment]
@greg-hellings Can you provide an example of that? Also can we set limits on the ci/cd workflows?

**Comment by greg-hellings** [comment]
So up in the top right corner of this page you'll see a button called "fork". If you click that it will create a fork under your user namespace. You then push your working branches to that repo and open a PR to this repo from your branch.

I'm sure there are docs that explain it in better detail than I just did there. But that is how people are supposed to work into a "golden standard" repo. It 1) cuts down on clutter in this repo, 2) keeps CI from picking up every commit into a feature branch, 3) keeps people from accidentally pushing master, 4) keeps tags out of this repo that shouldn't be there, 5) allows people who are not core contribs to contribute equally with everyone else, and I'm sure a host of other benefits I'm not thinking of at the moment.

**Comment by greg-hellings** [comment]
Yes, going between forks would be preferable, as this is the golden copy. That doesn't mean you have to redo this one, just in the future it would be better for things to live in your own fork until it's time to open a PR.

**Comment by jjaswanson4** [comment]
Following @greg-hellings's suggestion

**Pull request closed without merging**
